### PR TITLE
Disable plugins, helps when testing locally.

### PR DESCRIPTION
**Pull request by jschwartzentruber**

### CODE REVIEW

**Comment by jruderman** [comment]
Hmm. It is weird that we only test plugins when we happen to run DOMFuzz locally. On the other hand, [I have reported many bugs involving plugins](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=ALL%20reporter%3Ajrud%20comp%3Aplug&order=bugs.bug_id%20desc) and I'm not sure they're less valuable than other bugs. On the other other hand, I never made an effort to test plugins well (e.g. by creating evil Flash files or teaching DOMFuzz about the [Test Plug-in](https://dxr.mozilla.org/mozilla-central/source/dom/plugins/test/testplugin/README)’s APIs) so the bugs found have been incidental.

Without this pref, which plugins cause trouble? What kind of trouble?

If we do add this pref, it should go in the "Set additional prefs for fuzzing" section of the file.

**Comment by jschwartzentruber** [comment]
Flash. ASan was complaining about memory leaks from a bad flash update iirc. If you've found legitimate plugin bugs before then let's not do this (or add it but comment it out).

**Comment by jruderman** [comment]
How easy is it to tell LSan to ignore Flash leaks?

**Comment by jschwartzentruber** [comment]
I haven't looked, but that would be the right thing to do.

**Pull request closed without merging**
